; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lora_e5_mini]
platform = ststm32
board = lora_e5_mini
framework = arduino
build_flags =
	-D WAKE_INTERVAL_MS=15000UL
	-D HEARTBEAT_INTERVAL_MS=2592000000UL
	-D SIGNIFICANT_CHANGE_THRESHOLD=0.05f

; Force serial monitoring through your CP2102 adapter
monitor_speed = 115200

; If you are flashing directly via USB-C (DFU mode) or via ST-Link V2, 
; uncomment the appropriate line below:
; upload_protocol = dfu
upload_protocol = stlink
