; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = platformio_secrets.ini

[common]
build_flags =
	-D WAKE_INTERVAL_MS=5000UL
	-D HEARTBEAT_INTERVAL_MS=2592000000UL
	-D SIGNIFICANT_CHANGE_THRESHOLD=0.05f
	-D LOW_VOLTAGE_TRIGGER_MV=3200U
	-D LOW_VOLTAGE_RECOVERY_HYSTERESIS_MV=100U
	-D BATTERY_ADC_PIN=PA10
	-D BATTERY_DIVIDER_RATIO=2.0f
	-D BATTERY_SAMPLE_COUNT=32U
	-D BATTERY_ADC_SETTLE_MS=10U
	-D ADC_SAMPLINGTIME=ADC_SAMPLETIME_160CYCLES_5
	-D ADC_CLOCK_DIV=ADC_CLOCK_ASYNC_DIV256
	-D BATTERY_VREF_CALIBRATION_GAIN=0.9710f
	-D LORAWAN_REGION=EU868
	-D LORAWAN_JOIN_MAX_RETRIES=3
	-D LORAWAN_JOIN_RETRY_DELAY_MS=2000UL
	-D LORAWAN_TX_MAX_RETRIES=3
	-D LORAWAN_TX_RETRY_DELAY_MS=2000UL
	-D LORAWAN_FAKE_TRANSMIT_SUCCESS=1
	-D SENSOR_FAKE_MODE=1
	-D DISABLE_SLEEP_FOR_CALIBRATION=0
	-D __NO_INIT=

[env:lora_e5_mini]
platform = ststm32
board = lora_e5_mini
framework = arduino
build_flags = 
	${common.build_flags}
	${ttn.build_flags}
lib_deps =
	stm32duino/STM32duinoLoRaWAN@0.5.0
	stm32duino/STM32duino RTC@1.9.0
monitor_speed = 115200
upload_protocol = stlink
